### PR TITLE
integerMode option and turf sub-modules

### PR DESCRIPTION
**Pull request by ikkala**
New integerMode=true uses integer method of latest ngeohash. => 0.5.0

The turf module was quite large monolith, upgraded the version and took only the required sub-modules of turf. => 0.5.1

### CODE REVIEW

**Comment by derrickpelletier** [comment]
Thanks @ikkala, looks like a good addition.

Realizing that I should get some tests in here before I start accepting new features like this, especially ones outside my own familiarity. I'll whip up something really simple tonight or tomorrow and come back to this PR.

**Comment by ikkala** [comment]
Hi again,

Yes indeed, I omitted test development totally for the new feature, shame me. How have you generated the original test data?

But the real shame was, that after I did the turf library optimization, I managed to ignore the running of the existing tests. Well, after original pull request I run them and they failed.  :) Well, now the 0.5.2 fixes the issue by taking a bit older version of turf.intersection that supports the featurecollections.

**Comment by derrickpelletier** [comment]
Ah thanks for the update.

The original test data was sort of a brute force effort, manually comparing results. Technically you should be able to just run the same test using that integer option and compare the result count. All that is really differing here is the outputted hash, they should still correspond with the original methods. If those original tests still pass and your integer tests pass, all would be good

**Comment by ikkala** [comment]
That's true: It utilizes now the standard side tests for integerMode. Of course, the precision must be multiplied by 5 and because https://github.com/sunng87/node-geohash says about integer precision "Bit depth must be even" the odd ones are skipped.

**Comment by derrickpelletier** [comment]
That'll do! thanks :ok_hand:

**Pull request merged**
